#!/bin/bash

echo 'Setting Up Weeman On Termux'
echo 'Sit Back And Relax'
apt update
apt upgrade -y
apt install git python python2 curl proot figlet -y
cd $HOME 
git clone http://github.com/evait-security/weeman
mv -rf weeman $PREFIX/
