#!/bin/bash

echo 'Setting Up Weeman On Termux'
echo 'Sit Back And Relax'
apt update
apt upgrade -y
apt install git python python2 curl proot figlet -y
cd $HOME 
git clone http://github.com/evait-security/weeman
cp -rf weeman $PREFIX/share
rm -rf weeman
cd $HOME 
wget https://raw.githubusercontent.com/HackZonE404/SetupWeeman/master/uninstallwewman
wget https://raw.githubusercontent.com/HackZonE404/SetupWeeman/master/weeman
chmod +x *
cp -rf weeman $PREFIX/bin/
cp -rf uninstallweeman $PREFIX/bash
rm -rf weeman uninstallweeman
echo 'Successfully Installed Weeman Please Subscribe My Channel HackZonE'
